services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.1
    container_name: elasticsearch_quake
    # build: .
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      xpack.security.enabled: false 
      # ELASTIC_PASSWORD: Pa
      discovery.type: single-node
      ES_JAVA_OPTS: -Xmx512m -Xms512m
      node.name: esnode1 
      cluster.name: earthquake
    volumes:
          - ./elastic/data:/var/lib/elasticsearch
          - ./elastic/logs:/var/log/elasticsearch
    networks:
          - elasticnet

  kibana:
    image: docker.elastic.co/kibana/kibana:7.11.1
    container_name: kibana_quake
    ports:
      - '5601:5601'
      - '9600:9600'
    environment:
      SERVERNAME: kibana
      # elasticsearch.password: Pa
      # elasticsearch.username: sih 
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      ES_JAVA_OPTS: -Xmx512m -Xms512m
    networks:
      - elasticnet
    depends_on:
      - elasticsearch

volumes:
  logvolume01: {}

networks:
  elasticnet: {}

